/* ==========================================================================
 * x816_contract.h -- the X816 contract constants.
 *
 * GENERATED BY tools/contract.py -- DO NOT EDIT.
 * Edit X816_core/tools/contract.py and run:  python tools/contract.py --write
 *
 * This file is one half of the contract mechanism. The other half is
 * `contract.py --check`, which reads the sites that keep their own literal
 * -- x816.sv, the linker scripts, mksdcard.py -- and fails if any of them
 * has drifted from the table these constants came from.
 * ========================================================================== */

#ifndef X816_CONTRACT_H
#define X816_CONTRACT_H

/* ---- Image and load contract --------------------------------------------- */
/* Where the HPS loader drops an image, what marks it as one, and where */
/* control is handed to it. boot/boot.s, x816.sv's download path, exec.s and */
/* every linker script have to agree on all of it or a load lands on the zero */
/* page and the machine dies before it prints anything. */

#define X816_PROG_BASE      0x010000UL       /* loadable program image: OSD 'Load Image' and boot1.rom */
#define X816_PROG_ENTRY     0x010004UL       /* PROG_BASE + 4 -- the jmp in the image's own header */
#define X816_FW_BASE        0xF00000UL       /* resident kernel firmware image, boot2.rom (doc/KERNEL.md 3) */
#define X816_FW_ENTRY       0xF00004UL       /* FW_BASE + 4 */
#define X816_FW_FIRST_BANK  0xF0u            /* banks $F0-$FF are the firmware region, write-protected */
#define X816_MAGIC          "X816"           /* the four bytes at either base that say 'this is an image' */
#define X816_MAGIC_0        'X'
#define X816_MAGIC_1        '8'
#define X816_MAGIC_2        '1'
#define X816_MAGIC_3        '6'
#define X816_MAGIC_LE32     0x36313858UL     /* the same four bytes as one little-endian 32-bit read */
#define X816_IOCTL_PROG     0x0040u          /* MiSTer ioctl_index for boot1.rom (a program image) */
#define X816_IOCTL_FW       0x0080u          /* MiSTer ioctl_index for boot2.rom (the kernel firmware) */
#define X816_IOCTL_OSD_SLOT 0x01u            /* ioctl_index[5:0] for an OSD file pick */
#define X816_EXEC_STAGE     0x100000UL       /* where `run` parks an image before relocating it over PROG_BASE */
#define X816_EXEC_MAX       0xFF00u          /* largest image exec.s's single-pass copy can move (X is 16 bits) */

/* ---- Kernel ABI -- table, context and error codes ------------------------ */
/* doc/KERNEL.md sections 3-5. The table address is fixed forever; the */
/* kernel's bank-0 claim is carved out of every program's linker map so a */
/* program object cannot land on the kernel's direct page. */

#define KERN_TABLE      0x00FE00UL           /* 64 entries of `jmp long:`, one page */
#define KERN_ENTRIES    64                   /* entries in the table */
#define KERN_ENTRY_SIZE 4                    /* bytes per entry -- a jmp long: */
#define KERN_TABLE_END  0x00FEFFUL           /* last byte of the table page */
#define KERN_DP         0x2000u              /* the kernel's direct page; KENTER switches D here */
#define KERN_STATE      0x2000u              /* start of the kernel's bank-0 claim (KERNEL.md 3.1) */
#define KERN_STATE_END  0x2FFFu              /* last byte of the claim */

/* ---- MEM_ALLOC arena ----------------------------------------------------- */
/* The flat SDRAM the kernel hands out, doc/KERNEL.md 5.5. It starts at bank */
/* $20 because everything below is already claimed by somebody: bank $00 is */
/* BRAM, $01-$0F is the program image (x816-lib.scm's Code region), and */
/* $10-$1F is FarRAM and the EXEC staging area. It stops below $F0 because */
/* that is the write-protected firmware. Nothing here is a preference -- if */
/* the linker maps and this arena ever disagreed, a program's own `far` data */
/* and a kernel allocation would be the same bytes, which is silent. */

#define X816_HEAP_TABLE  0x200000UL          /* one page of kernel bookkeeping, never handed out */
#define X816_HEAP_BASE   0x200100UL          /* first byte MEM_ALLOC may return */
#define X816_HEAP_END    0xEFFFFFUL          /* last byte of the arena, inclusive */
#define X816_HEAP_GRAIN  0x100u              /* allocations are rounded up, and start, on a page */
#define X816_HEAP_BLOCKS 32                  /* live allocations at once -- a fixed table, not a free list */

/* ---- Kernel error codes -------------------------------------------------- */
/* Returned in C with carry SET. Zero is never an error, so a caller that only */
/* checks carry and a caller that checks the code agree. */

#define KERR_NOSYS    1                      /* call number not implemented in this build */
#define KERR_NOTFOUND 2
#define KERR_NOSPACE  3
#define KERR_BADARG   4
#define KERR_IO       5
#define KERR_EXISTS   6
#define KERR_NOTEMPTY 7

/* ---- I/O page, bank $00 page $9F ----------------------------------------- */
/* Deliberately the same layout as the Commander X16 for $9F00-$9F7F so X16 */
/* register offsets port over unchanged; $9F80-$9F8F is X816's own. */

#define X816_IO_PAGE        0x9F00u          /* bank $00 only */
#define X816_VIA1           0x9F00u
#define X816_VIA2           0x9F10u
#define X816_VERA           0x9F20u          /* $9F20-$9F3F */
#define X816_YM             0x9F40u
#define X816_SYSCTL         0x9F80u          /* bit 0 boot overlay, bit 1 E flag (r/o) */
#define X816_SYSCTL_LAST    0x9F8Fu          /* end of the SYSCTL decode */
#define X816_SYSCTL_OVERLAY 0x01u            /* bit 0: boot ROM overlay enable */
#define X816_SYSCTL_EMU     0x02u            /* bit 1: CPU E flag, read-only */
#define X816_SD_LBA         0x9F81u          /* $9F81-$9F84 block number, LE */
#define X816_SD_MEM         0x9F85u          /* $9F85-$9F87 DMA address, LE (READ only) */
#define X816_SD_COUNT       0x9F88u          /* blocks to transfer, 1-255 */
#define X816_SD_CMD         0x9F89u          /* WRITE ONLY. 1 READ 2 WRITE 3 READBUF 4 RESET */
#define X816_SD_STATUS      0x9F8Au          /* READ ONLY. b0 busy, b1 error, b7 present */
#define X816_SD_GAP         0x9F8Bu          /* MUST STAY UNMAPPED -- see sd_block.sv */
#define X816_SD_DATA        0x9F8Cu          /* block-buffer window, auto-incrementing */
#define X816_KBD_COUNT      0x9F8Du          /* keyboard diagnostic counters, $9F8D-$9F8F */
#define X816_BOOT_BASE      0xFF00u          /* boot ROM read overlay, bank $00 */
#define X816_BOOT_SIZE      0x100u           /* and it is exactly one page */

/* ---- Card layout --------------------------------------------------------- */
/* The demo card built by tools/mksdcard.py, and the one path that is compiled */
/* into a binary: goshell reloads the shell by name. */

#define X816_DEMO_DIR   "/DEMO"
#define X816_SHELL_PATH "/DEMO/SHELL.BIN"    /* goshell.c reloads this on ESC */

/* ---- kernel call numbers ------------------------------------------- */
/* The numbering leaves gaps between groups on purpose: adding FS_TRUNCATE  */
/* later must not renumber MEM_ALLOC, because a renumber breaks every       */
/* program already built. kerntab.s's table is generated from the same      */
/* rows, so a number here and a position there cannot disagree.             */

/* console, 0-15 */
#define K_CON_PUTC     0                 /* C = character */
#define K_CON_PUTS     1                 /* C:X = 24-bit pointer to a NUL-terminated str */
#define K_CON_GETC     2                 /* -> C = character, blocking */
#define K_CON_GETKEY   3                 /* -> C = character, or 0 if none */
#define K_CON_CLS      4
#define K_CON_GOTOXY   5                 /* C = column, X = row */
#define K_CON_GETXY    6                 /* -> C = column, X = row */
#define K_CON_PUTRAW   7                 /* C = column, X = row, Y = glyph code */

/* filesystem, 16-31 */
#define K_FS_OPEN     16
#define K_FS_CLOSE    17
#define K_FS_READ     18
#define K_FS_WRITE    19
#define K_FS_SEEK     20
#define K_FS_SIZE     21
#define K_FS_DELETE   22
#define K_FS_RENAME   23
#define K_DIR_OPEN    24
#define K_DIR_NEXT    25
#define K_DIR_CLOSE   26
#define K_FS_CHDIR    27
#define K_FS_GETCWD   28
#define K_FS_MKDIR    29
#define K_FS_RMDIR    30

/* programs, 32-39 */
#define K_EXEC        32                 /* C:X = path; does not return on success */
#define K_EXIT        33                 /* C = status; does not return */

/* memory, 40-47 */
#define K_MEM_ALLOC   40                 /* C:X = 32-bit size -> C:X = address */
#define K_MEM_FREE    41                 /* C:X = address */

/* system, 48-63 */
#define K_SYS_VERSION 48                 /* -> C = (major << 8) | minor */

#endif /* X816_CONTRACT_H */
